name: CI Artifact Build

on:
  push:
    branches:
      - develop
      - '^release'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Preparation
      id: prep
      run: |
          VERSION=${GITHUB_SHA::8}
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H-%M-%SZ')
          echo ::set-output name=VERSION::${VERSION}
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm64/v8
        tags: lkravi/eks_bp_demo:${{ steps.prep.outputs.VERSION }}, lkravi/eks_bp_demo:${{ steps.prep.outputs.BUILD_DATE }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}